### ISSUE TITLE
ps2sdk now only works on latest pcsx2 

### ISSUE THREAD

**Issue by rodrigo1593** [ps2dev/ps2sdk#546] opened 2024-03-05 17:09 UTC
it only works on latest versions but not on older like 1.4.0 or i guess the first 1.7 version

**Comment by lucasoliveirateles** [comment] 2024-03-07 16:27
Yeah, absolutely. The whole setup enviroment works with the PCSX2 Nightly version. Version stable of PCSX2 is not stable.

**Comment by fjtrujy** [comment] 2024-03-12 20:59
In theory, it should work, however, PCSX2 didn't have before implemented filesystem in the previous versions, so if you tried to load files from the host, it may not work properly.
Could you tell me what kind of example are you executing? and also what's the motivation for running such a legacy PCSX2 version?

Cheers.

**Comment by rodrigo1593** [comment] 2024-03-31 00:54
since latest update to enceladus with the new ps2sdk it just doesn't load the scripts, it just say "enceladus error",, im trying to execute the pads example no modification to it.... 


let me tell you that its not possible for me to run browser & emulator at the same time without getting my system locked (on windows 10 and later)

i saw it now, on windows 8.1 im using a "modified pcsx2 1.7" (qt version) someone made it backwards compatible with windows 7 if i remember correctly maybe i am wrong hehe....

simply put, the motivation is that since windows 8.1 (64 bits on 2gb of ram, original iso no mods LOL)... works really quick, no need to wait as an idiot, i can listen to music and relax while doing some things....

sincerely i was surprised that the support for older versions was thrown away,

also it happens with athenaenv too

------------------LMAO----------------------------------------------------------
i tried to get a lite version of windows 10, found one that worked nicely, less ram usage (OK, OK 2016 BUILD ltsb), it doesn't work... got error on library, saw on internet, something related to outdated os to run pcsx2 1.7.xxxx nightly, tried tiny10 (ntdev), lags with just the emulator open, but latest work with enceladus.... 
-----------------------------------------------------------------------------------

**Comment by israpps** [comment] 2024-03-31 02:38
This is not SDK or Enceladus issue.

This is emulator/os issue. Enceladus compiled by latest SDK worked last time I tried (1 week ago)

**Comment by fjtrujy** [comment] 2024-03-31 11:47
> since latest update to enceladus with the new ps2sdk it just doesn't load the scripts, it just say "enceladus error",, im trying to execute the pads example no modification to it....
> 
> let me tell you that its not possible for me to run browser & emulator at the same time without getting my system locked (on windows 10 and later)
> 
> i saw it now, on windows 8.1 im using a "modified pcsx2 1.7" (qt version) someone made it backwards compatible with windows 7 if i remember correctly maybe i am wrong hehe....
> 
> simply put, the motivation is that since windows 8.1 (64 bits on 2gb of ram, original iso no mods LOL)... works really quick, no need to wait as an idiot, i can listen to music and relax while doing some things....
> 
> sincerely i was surprised that the support for older versions was thrown away,
> 
> also it happens with athenaenv too
> 
> ## ------------------LMAO----------------------------------------------------------
> i tried to get a lite version of windows 10, found one that worked nicely, less ram usage (OK, OK 2016 BUILD ltsb), it doesn't work... got error on library, saw on internet, something related to outdated os to run pcsx2 1.7.xxxx nightly, tried tiny10 (ntdev), lags with just the emulator open, but it does work with enceladus....

The issue is basically that PCSX2 didn't emulate previously the `host` unit properly.
This is something that was implemented in PCSX2 a couple of years ago..., so previous `PCSX2` versions won't work properly with software that use `host`. In order to execute athena/enceladeus with previous PCSX2 versions will require putting everything under the USB or MC unit, and the boot the binary from `wLE`.

Ok, so it is clear that this is not an issue with the `ps2toolchain` however it is an issue with PCSX2.
Closing the issue then, please reopen it if you consider it.

Cheers.

**Closed by fjtrujy** 2024-03-31 11:47 UTC
